app:
    resource: "@AppBundle/Controller/"
    type:     annotation

cms_ulysse:
    resource: "@CmsUlysseBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
