# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    ulysse_user_registration:
         class: CmsUlysseBundle\Form\Type\RegistrationType
         arguments: [%fos_user.model.user.class%]
         tags:
            -  { name: form.type }