<?php

namespace CmsUlysseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function findCategsUp()
    {
        $qb = $this->createQueryBuilder('c');
        $qb->where('c.categ_up is null')
           ->orderBy('c.id', 'ASC');

        return $qb->getQuery()->getResult();
    }

    public function findCategsDown()
    {
        $qb = $this->createQueryBuilder('c');
        $qb->where('c.categ_up is not null')
           ->orderBy('c.categ_up', 'ASC');


        return $qb->getQuery()->getResult();
    }

    public function findCategsUpForm()
    {
        $qb = $this->createQueryBuilder('c');
        $qb->where('c.categ_up is null')
           ->orderBy('c.id', 'ASC');

        return $qb;
    }

    public function findCategsDownForm()
    {
        $qb = $this->createQueryBuilder('c');
        $qb->where('c.categ_up is not null')
            ->orderBy('c.categ_up', 'ASC');


        return $qb->getQuery()->getResult();
    }

}
