<?php

namespace CmsUlysseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function findNoValidate()
    {
        $qb = $this->createQueryBuilder('p');
        $qb->where('p.isValid = 0');

        return $qb->getQuery()->getResult();
    }

    public function findValidate()
    {
        $qb = $this->createQueryBuilder('p');
        $qb->where('p.isValid = 1');

        return $qb->getQuery()->getResult();
    }
}
