<?php

namespace CmsUlysseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{

    public function findProductsByCategoryUp($category, $limit=null)
    {
        $qb = $this->createQueryBuilder('p');
        $qb
            ->leftJoin('p.categories', 'c')
            ->leftJoin('c.categ_up', 'cu')
            ->leftJoin('p.usersProducts', 'up')
            ->andWhere("cu.id = :category")
            ->andWhere("up.id is not null")
            ->setParameter('category', $category);
        if($limit != null){
            $qb->setMaxResults($limit);
        }

        return $qb->getQuery()->getResult();
    }

    public function findNewProductsByCategoryUp($category, $limit=null)
    {
        $qb = $this->createQueryBuilder('p');
        $qb
            ->leftJoin('p.categories', 'c')
            ->leftJoin('c.categ_up', 'cu')
            ->leftJoin('p.usersProducts', 'up')
            ->andWhere("cu.id = :category")
            ->andWhere("up.id is not null")
            ->addOrderBy("up.id", "DESC")
            ->setParameter('category', $category);
        if($limit != null){
            $qb->setMaxResults($limit);
        }

        return $qb->getQuery()->getResult();
    }
}
