<?php

namespace CmsUlysseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserProductRepository extends EntityRepository
{
    public function findMarketProducts()
    {
        $qb = $this->createQueryBuilder('p');
        $qb->where('p.qty != 0');

        return $qb->getQuery()->getResult();
    }
}
