<?php

namespace CmsUlysseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserProductRepository extends EntityRepository
{
    public function findSearchProducts($search, $category = null)
    {
        $qb = $this->createQueryBuilder('u');
        $qb->join('u.product', 'p')
            ->addSelect('p')
            ->leftJoin('p.categories', 'c')
            ->addSelect('c')
            ->where('p.name LIKE :search')
            ->orWhere('p.description LIKE :search')
            ->setParameter('search', '%'.$search.'%');

        if ($category === null) {
            $qb->orWhere('c.name LIKE :search');

        } else {
            $qb->andWhere("c.id = :category")
               ->setParameter('category', $category);
        }


        return $qb->getQuery()->getResult();
    }

    public function findBest($limit = 10)
    {
        $qb = $this->createQueryBuilder('u');
        $qb->join('u.commands', 'c')
           ->addSelect('c, SUM(c.qty) as somme')
           ->groupBy('c.product')
           ->orderBy('somme', 'DESC')
           ->setMaxResults(10)
        ;

        return $qb->getQuery()->getResult();
    }
}
