<?php

namespace CmsUlysseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserProductRepository extends EntityRepository
{
}
